### PR TITLE
Do not add TimePlugin

### PR DESCRIPTION
**Pull request by elsid**
If application adds TimePlugin too, this breaks time delta computation. See [this](https://github.com/jcornaz/heron/pull/301/files#r1018542709) comment for more details.

Applications should add all required plugins before adding heron plugins.

### CODE REVIEW

**Review by jcornaz — CHANGES_REQUESTED** [review]
Hi, 

Yes, indeed you're right. Thank you very much for the report and for your contribution!

If possible, I would prefer to improve the situation without making a breaking change. I think it  could be achieved by creating new plugins and deprecating the old ones. In concept that could look like this:

```rust
#[derive(Debug, Default)]
#[non_exhaustive]
pub struct RapierPluginSlim;
impl Plugin for RapierPluginSlim {
  fn build(&mut self, app: &mut App) { /* move here the installation, except for the TimePlugin */ }
}

#[deprecated(reason = "Please use `RapierPluginSlim`instead")]
pub struct RapierPlugin;
impl Plugin for RapierPlugin {
  fn build(&mut self, app: &mut App) {
    app.add_plugin(TimePlugin::default()).add_plugin(RapierPluginStruct::default());
  }
}
```

The name `RapierPluginSlim` is maybe not great, but there is no need to bikeshed too much as I would even consider `RapierPluginV2` to be better than a breaking change, and it may easily be improved later without breaking the API.

**Comment by elsid** [comment]
I don't agree to make the change without breaking the API. Let me explain.

I've found the issue when tried to update my project from bevy 0.7 and heron 3.1.0 to 0.8.1 and 4.0.2 respectively. For me 4.0.2 did a breaking change because of adding `TimePlugin` by `RapierPlugin` (`TimePlugin` didn't exist before bevy 0.8). I'm not sure whether it was it intentional but I think I'm not the only one who faced this problem. Bevy documentation suggests to use its plugin groups like `MinimalPlugins` and `DefaultPlugins` depending on the use case and both add `TimePlugin`. I expect most of applications to follow this approach. Maybe there are applications which cherry-pick specific plugins and don't use plugin groups. IIUC your concern is about these applications which will break by this pull request because they don't add `TimePlugin` and rely on `RapierPlugin` doing it. I'm not sure it's a good idea to avoid breaking API change just to keep current potentially incorrect behaviour for the benefit of such projects. This only complicates the update from 3.1.0 to 4 for regular users.

Fundamental problem here is probably a lack of mechanism to prevent plugin duplication in bevy or basically there is no plugin dependency management (https://github.com/bevyengine/bevy/issues/69). I think https://github.com/jcornaz/heron/pull/301 did a mistake without understanding the problem in attempt to fix tests. Unfortunatelly there is no cheap fix for such mistakes. Breaking API change could save time for developers who are not aware of the problem yet which I think is better than providing smooth update for applications already using 4.0.2.

**Comment by jcornaz** [comment]
Yes, it was a mistake to install the `TimePlugin`. But why this mistake was made though? It is my conviction, that the root cause is how bevy carelessly breaks its API all the time and put pressure on plugin authors who have to upgrade ASAP because their plugin suddenly became obsolete.

I am aware of the technicalities of plugin management with bevy. But that's an unimportant implementation detail. 

I feel very strongly against breaking changes in general, and I am very unhappy with how bevy treats them. In fact, [that's why I decided to discontinue heron](https://github.com/jcornaz/heron/discussions/317). 

I do not want to behave as they do. Adding a new plugin, and deprecating the old one is very graceful. All users get notified that the old one is deprecated and can easily use the new one, without being forced to make immediate action if they don't want to.

I am sorry, but I won't merge a breaking change. There will not be a heron 5.0.0.

**Comment by jcornaz** [comment]
Just a quick addition to my previous message, as I'd like to respond to this point in particular:

> This only complicates the update from 3.1.0 to 4 for regular users.

Publishing heron 5 would not make it easier for migrating from 3 to 4. But a non-breaking change (in 4.1) would help, as the users would see the deprecation and could understand faster what is the problem.

And the very reason why users even have to migrate is because of the breaking changes in bevy 0.8 and heron 4. If it wasn't for those breaking changes the problem would not exist in the first place. Which is just yet another fact supporting my point: *we should not make breaking changes!*

**Review by jcornaz — APPROVED** [review]
I actually changed my mind, and I accept this change as-is despite being a breaking change. After the release of heron 5 I'll publish a heron 4.1 leveraging the [semver trick] to make heron 4 compatible with heron 5.

Sorry for my epidermic reaction.

Bevy's lack of care for API stability (which lead me to discontinue heron) combined to my experience of having to deal with breaking changes in languages that are much less good than rust,  I started to have a very strong (maybe extreme position) against breaking changes.

I still mostly think that breaking changes are evil, and that they are overused by the software industry. So many of them could be avoided very easily.

However, I now realize that for a rust library (but only for a rust library), a breaking change maybe acceptable if (and only if):
* It makes the API significantly better than any non-breaking change I can think of. (your change does fulfill this requirement IMO)
* The [semver trick] can be used (and *is* used) to keep the previous major version mostly compatible with the new one (enabling a smoother upgrade path for consumers, as they may use both major version together for a while)
* The breaking change is published immediatly (it shouldn't wait for 3 months to be batched with 100's of other breaking changes...)

[semver trick]: https://github.com/dtolnay/semver-trick

**Pull request merged**
