### PR TITLE
feat: make `CollisionLayers::none` and `CollisionLayers::from_bits` const functions

### PR DESCRIPTION
**Pull request by Shatur**
Harmless change, I need this to make nicer tests for #224 :)

### CODE REVIEW

**Comment by jcornaz** [comment]
Do you need all of them? I would like to keep `const` methods to a minimum (because it is not possible to remove it later without breaking the API)

But I don't mind introducing `const` when driven by a need. I just want to make sure we mark `const` only what we need :-)

**Comment by Shatur** [comment]
Actually no, I only need `from_bits`. But I thought that simple methods, such as getters and comparsion could be const. Do you think I thould revert other functions? If yes, which one?

**Comment by jcornaz** [comment]
Ok, thanks. So you can keep `const` the two constructors (`none` and `from_bits`), and revert it for the other members.

**Review by jcornaz — APPROVED** [review]
thanks

**Pull request merged**
