### PR TITLE
Convex Decomposition

### PR DESCRIPTION
**Pull request by zicklag**
Is this something you'd be open to? I'm going to need it in my game, assuming my algorithm for generating sprite collision shapes works out.

There's maybe a few controvercial changes:

- I had to add 2d and 3d features to the heron_core because the dimensions of an array used to define the convex decomposition is different in different dimensions
- I had to add rapier2d and rapier3d as dependencies to heron_core because I needed access to a struct for the parameters that was in those crates
- I currently copy-and-paste a struct and an enum from `parry` because the parry struct doesn't implement Debug and Clone. ( I opened a PR: https://github.com/dimforge/parry/pull/40  )

Depends on #119 ( sort of, I could rebase it but it woudl be easier not to ).

### CODE REVIEW

**Comment by jcornaz** [comment]
Thanks for the suggestion and contribution.

For this one I'll have to think about it. I'll do my best to move it forward by either merging it or propose an alternative sollution. But no promises.

To make easier for me, do you mind sharing more details about the use-case?

> I had to add rapier2d and rapier3d as dependencies to heron_core because I needed access to a struct for the parameters that was in those crates

That would be against the idea of separating `heron_core` (API only, agnostic of the physics engine) and `heron_rapier` (Implementation using rapier).

That being said, I realized that my split of the crates was more caused by habbits comming from other programming languages. And I eventually started to think that in rust the separations should be:
* different *domain* contexts (or subcontexts): Separate crates (e.g. collisions vs physics)
* different *technology* layers: same crate, different cargo features (e.g. rapier vs another physics engine)

So, I'd be eventually open to add `rapier` to `heron_core`. *But, if that happens it should be an optional dependency.*

**Comment by zicklag** [comment]
> That would be against the idea of separating heron_core (API only, agnostic of the physics engine) and heron_rapier (Implementation using rapier).

Gotcha. I hadn't fully thought out the implications there, but I felt like there was some intention like that. I haven't thought deeply about it yet, but the way you have it doesn't seem like a bad design.

> To make easier for me, do you mind sharing more details about the use-case?

In my game I have a non-convex sprite that I need to generate a collision shape from. I'm still working on an algorithm to translate the sprite alpha channel to a polyline that I can pass to rapier's convex decomposition algorithm. The plan so far is to take sprite → polyline around sprite's alpha → collection of convex hulls representing the sprite's collision shape.

That said, I'm realizing that I can use rapier to generate the convex collisions and then use those points to create a set of normal heron convex hull shapes, which heron already has. That wouldn't require a convex decomposition shape for heron, then.

Would you be open to a `heron::CollisionShape::Compound(Vec<CollisionShape>)` that could be used to create compound shapes made up of multiples? I think that would solve my use-case.

**Comment by jcornaz** [comment]
> Would you be open to a heron::CollisionShape::Compound(Vec<(Transform, CollisionShape)>) that could be used to make a single collision shape entity that was made out of many convex hulls, or other shapes for that matter? I think that would solve my use-case.

Yes, a compound shape sounds good to me. You can go with that.

I would even be up to add in `heron_rapier` a utility function to create a `CollisionShape::Compound` by using rapier's convex decomposition algorithm.

> In my game I have a non-convex sprite that I need to generate a collision shape from. I'm still working on an algorithm to translate the sprite alpha channel to a polyline that I can pass to rapier's convex decomposition algorithm. The plan so far is to take sprite → polyline around sprite's alpha → collection of convex hulls representing the sprite's collision shape.

Just out of curiosity, (if you can divulgate such information) why do you need such precision for the collision shape to match the sprite? Often approximating the sprite with boxes, sphere or capsule is enough, and much more performant. And it's often even  desirable to "cheat" and intentionally give the collision shape a smaller (or bigger) size than the sprite so that the game feals better to the player.

**Comment by zicklag** [comment]
> Yes, a compound shape sounds good to me. You can go with that.

Cool. I've got #122 working for that, other than debug rendering.

> I would even be open to add in heron_rapier a utility function to create a CollisionShape::Compound by using rapier's convex decomposition algorithm.

OK, cool I'll probably do that too then.

> Just out of curiosity, (if you can divulgate such information) why do you need such precision for the collision shape to match the sprite? Often approximating the sprite with boxes, sphere or capsule is enough, and much more performant. And it's often even desirable to "cheat" and intentionally give the collision shape a smaller (or bigger) size than the sprite so that the game feals better to the player.

It's actually kind of an ease-of-use thing. I'm trying to build a simple 2D game engine/kit that lets you easily edit maps using [LDtk](https://ldtk.io), but there's the question of how to handle map collisions. Currently the idea is that you have a separate map layer that is used just for collisions. In this screenshot, for instance, the green overlay is the collision layer:

image

This is intuitive and easy to manage even for non-programmers. The only alternative would be to add collision shape metadata manually using pixel coordinates to specify polygons in YAML format, which would be highly unintuitive. I would feel the need to create a custom collision editor. ( It's worth noting that the Tiled map editor did have a collision editor, which would have been a great option, but LDtk is a lot easier to use in other ways. )

What I want to do is read the collision layer, and then generate a collision mesh from that collision layer. Player collisions would be generated in a similar way, with separate sprites for their collision shape and for their animations.

---

Honestly its the first time I'm getting into game development and maybe there are better ways to approach this, but I think it's worth a try and I'll move on to something else if it doesn't work.

**Comment by jcornaz** [comment]
Ah, thanks for the explanation I get it now.

I use LDtk too, and what I do is I spawn a collision shape per tile (only on tiles where it make sense ofc). Which is simple and intuitive enough for me. But I aggree it is not for everyone, and not even for every game (as it also comes at a performance cost).

**Comment by zicklag** [comment]
> I use LDtk too, and what I do is I spawn a collision shape per tile (usually writing things like `collision` or `collision-up` in the tile data). Which is simple and intuitive enough for me.

You know using preset flags like `collision`, `collision-up`, etc. is actually a great idea that I didn't think of. Much simpler than setting manual coordinates and probably works for the large majority of tiles with no problem. I'll probably do that if my current strategy doesn't work. :) :+1:

**Pull request closed without merging**
