### PR TITLE
chore(deps)!: require bevy 0.6

### PR DESCRIPTION
**Pull request by jcornaz**
Preparing for updating to bevy 0.6.

Remaining tasks:

* [x] Use bevy 0.6 from crates.io
* [x] Restore or remove debug-2d (restored)
* [x] Restore or remove debug-3d (removed)
* [x] Address the warnings
* [x] Update the changelog
* [x] Update the readme

### CODE REVIEW

**Comment by nicopap** [comment]
I'll assume responsibility of getting bevy_debug_lines to work on `0.6` since I'm the one who introduced the dependency. [Here is the WIP PR](https://github.com/Toqozz/bevy_debug_lines/pull/10).

**Comment by jcornaz** [comment]
Thanks @nicopap. You shouldn't feel obliged ;-). But I am of course happy to see that works is being done to migrate projets that heron depends on.

Just for information, I am going to be away-from-code next week. So if bevy 0.6 is published this december, I may not have time to look at it before january.

**Comment by Shatur** [comment]
0.6 was released!

**Comment by jcornaz** [comment]
This is released as `1.0.1-rc.1`.

I removed the `debug-3d` feature while waiting for `bevy_debug_lines` to be compatible with bevy 0.6

**Pull request merged**
